name: batleague
description: No, I'm Batman

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  double_back_to_close_app: ^2.1.0
  cached_network_image: ^3.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: opensans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf