// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIg1H8_DrlMAcw3JSIYEdELItrIUScV6w',
    appId: '1:626783703142:web:16c039671b9f3635ae5da7',
    messagingSenderId: '626783703142',
    projectId: 'batleague',
    authDomain: 'batleague.firebaseapp.com',
    databaseURL: 'https://batleague-default-rtdb.firebaseio.com',
    storageBucket: 'batleague.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFxfpagWrA5q3xms-FTug3klrsFVwYHI0',
    appId: '1:626783703142:android:823a967d5425d3c0ae5da7',
    messagingSenderId: '626783703142',
    projectId: 'batleague',
    databaseURL: 'https://batleague-default-rtdb.firebaseio.com',
    storageBucket: 'batleague.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWLk6FpYXUhZ4NHPBI-5mLj4QLwFC4Nsg',
    appId: '1:626783703142:ios:d58e4e39ffad7394ae5da7',
    messagingSenderId: '626783703142',
    projectId: 'batleague',
    databaseURL: 'https://batleague-default-rtdb.firebaseio.com',
    storageBucket: 'batleague.appspot.com',
    iosClientId: '626783703142-pq9ml83bvjtbm2rst0ddu85rge00l69j.apps.googleusercontent.com',
    iosBundleId: 'com.example.batleague',
  );
}
